version: '3.8'

services:
  frontend:
    build: ./frontend/admin-one-vue-tailwind-master
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: iscte_spot
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
